apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  # namespace: argocd
data:
  policy.csv: |
    # Groups: g, <subject>, <role>
    g,           admin,     role:admin
    # g,           developer, role:developer
    # g,           readonly,  role:readonly

    p, role:admin, *, *, */*, allow

  policy.default: ""

  scopes: '[groups, email]'

